[package]
name = "gyg-eventsource"
version = "0.0.1"
edition = "2021"
description = "an eventsource implementation on top of eventstore"
repository = "https://github.com/galakhygame/gyg-eventsource"
license-file = "LICENSE"
keywords = ["eventsource", "eventsourcing", "eventstore"]
categories = ["database"]

[dependencies]
async-trait = "0.1"
eventstore = "2.2"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.1", features = ["v4", "serde"] }
tokio = "1.26"
thiserror = "1.0"
strum_macros = "0.25"

[dev-dependencies]
rand = "0.8.5"
redis= { version = "0.22", features = ["tokio-native-tls-comp"] }
