name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      evenstore:
        image: eventstore/eventstore:24.2.0-bookworm-slim
        env:
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_RUN_PROJECTIONS: All
          EVENTSTORE_START_STANDARD_PROJECTIONS: true
          EVENTSTORE_EXT_TCP_PORT: 1113
          EVENTSTORE_HTTP_PORT: 2113
          EVENTSTORE_INSECURE: true
          EVENTSTORE_ENABLE_EXTERNAL_TCP: true
          EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true
        ports:
          - "1113:1113"
          - "2113:2113"
      redis:
        image: redis:7.2.4-bookworm
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
      - name: Run clippy
        run: cargo clippy --all-features -- -D clippy::correctness -D clippy::complexity -D clippy::pedantic -D clippy::nursery -D clippy::perf -D clippy::cargo -D clippy::all -D clippy::expect_used

